#!/bin/bash

# Webdev CLI helps you quickly create and edit html/css projects.
# Author: Celina Yousief

bad_arg(){
		
	echo "Bad Argument!"
	echo
	echo "Usage: webdev -nb [params]"
	echo "	-n <filename> : New html skeleton in <filename>."
	echo "	-nb : New html skeleton using Bootstrap 4. (Coming soon)"
}

generate_skeleton(){

	cat << _EOF_
<!doctype html>
<html lang=en>

<head>
	<title>HTML Template example</title>
</head>

<body>

</body>

</html>
_EOF_
}

case $1 in
	
	-new|-n|-N)
		#TODO create new html skeleton
		#echo "New html skeleton"
		if [ -z $2 ]
		then
			bad_arg
		else
			generate_skeleton > $2
		fi
		;;

	-newb|-nb|-NB)
		#TODO create new html skeleton with Bootstrap
		echo "Coming Soon"
		;;
	
	*)
		bad_arg
		;;
esac


