#!/bin/bash

# Webdev CLI helps you quickly create and edit html/css projects.
# Author: Celina Yousief

bad_arg(){

	echo "Usage: webdev <options> [params]"
	echo "	-h : Usage and options."
	echo "	-n <filename> <filename2> ... : New html skeleton in <filename(s)>."
	echo "	-nb <filename> <filename2> ... : New html skeleton using Bootstrap 4 in <filename(s)>."
	echo "	-nbj <filename> <filename2> ... : New html skeleton using Bootstrap 4 with JavaScript in <filename(s)>."
}

generate_skeleton(){

	cat << _EOF_
<!doctype html>
<html lang=en>

<head>
	<title>HTML Template example</title>
</head>

<body>

</body>

</html>
_EOF_
}

generate_boot_skeleton(){
	cat << _EOF_
<!doctype html>
<html lang=en>

<head>
	<title>HTML Template example</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>

<body>

</body>

</html>
_EOF_
}

generate_bootj_skeleton(){
	cat << _EOF_
<!doctype html>
<html lang=en>

<head>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
	<title>HTML Template example</title>
</head>

<body>

</body>

</html>
_EOF_
}


case $1 in

	-help|-h-|-H)
		bad_arg
	;;
	
	-new|-n|-N)
		#create new html skeleton
		#echo "New html skeleton"
		if [ -z $2 ]
		then
			bad_arg
		else	
			for i in "${@:2}"
			do
    		generate_skeleton > $i
			done
		fi
	;;

	-newb|-nb|-NB)
		#create new html skeleton with Bootstrap
		#echo "Coming Soon"
		if [ -z $2 ]
		then
			bad_arg
		else
			for i in "${@:2}"
			do
    		generate_boot_skeleton > $i
			done
		fi
	;;

	-newbj|-nbj|-NBJ)
		#creat new html skeleton with Bootstrap and Javascript
		if [ -z $2 ]
		then
			bad_arg
		else
			for i in "${@:2}"
			do
    		generate_bootj_skeleton > $i
			done
		fi
	;;

	*)
		bad_arg
	;;
esac


